### ISSUE TITLE
--output-eight doesn't seem to work

### ISSUE THREAD

**Issue by IanHeywood** [kmbasad/eidos#9]
I still get a single FITS file when I set the --output-eight (or -o8) option, whether or not I specify a prefix.

**Comment by SpheMakh** [comment]
Are you using the latest master branch?

I just ran this:

```
eidos --pixels 512 --freq 850 1760 64 --diameter 6 --coefficients-file input/meerkat_coeff_dict.npy --prefix MeerKAT-LBand-PB-64chans --output-eight 
```

and got the eight FITS files

**Comment by IanHeywood** [comment]
I am using the latest master, I installed it as per the instructions shortly before I filed this issue.

When I run your command I get eight files. But when I request only a single frequency I don't:

```
eidos --output-eight -p 1024 -d 3 -f 1280 -c eidos/eidos/data/meerkat_coeff_dict.npy -P beamtest
```

**Comment by IanHeywood** [comment]
Naively trying to get around this by passing three values to freq in order to force a single channel causes a crash:

```
$ eidos --output-eight -p 1024 -d 3 -f 1280 1281 1 -c eidos/eidos/data/meerkat_coeff_dict.npy -P beamtest21
1280.0
Traceback (most recent call last):
  File "/home/ianh/.local/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/home/ianh/.local/lib/python2.7/site-packages/eidos/create_beam.py", line 58, in main
    write_fits_eight(data, nu, args.diameter, filename)
  File "/home/ianh/.local/lib/python2.7/site-packages/eidos/util.py", line 89, in write_fits_eight
    write_fits_cube(data[i,j,:,:,:].real, freqs, diameter, filename+'_re.fits')
  File "/home/ianh/.local/lib/python2.7/site-packages/eidos/util.py", line 64, in write_fits_cube
    cdelts = [diam/beam.shape[-2], diam/beam.shape[-1], fMHz[1]-fMHz[0]]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

None of this is disastrous of course, I can just access the planes I need from the (hyper)cube, but it seems like a legit bug.

Cheers.

**Comment by kmbasad** [comment]
The bug should be fixed now. And also I added the Stokes/Mueller formalism, so the I-beam can be calculated by adding `-S I` option. Help file has been updated as well.

**Comment by IanHeywood** [comment]
Awesome, thanks @kmbasad, @SpheMakh

**Comment by IanHeywood** [comment]
My understanding (which may be way off) is that the Stokes I beam is the one I should use to naively correct for the primary beam in the image plane, i.e. by dividing the map by the beam (and weighting by the square of the Stokes I beam when forming a linear mosaic).

However when I do this the fluxes are biased high (by factors up to ~3), i.e. the Eidos Stokes I beam is much narrower than one would expect.

Maybe someone can verify this independently, or tell me if I have misunderstood something.

Thanks.

**Comment by kmbasad** [comment]
Hi Ian,

Do you see this problem even now?
